---
ID: "9389d447-375e-4eb6-8a2e-682fac149c88"
Parent: "e81141e2-8ed0-4072-94a8-768d256da4fc"
Template: "e81141e2-8ed0-4072-94a8-768d256da4fc"
Path: /sitecore/templates/Feature/Blog/_BlogAuthor/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04afb3a6-5910-4fe2-af75-9042ebfb5e96"
      Hint: BlogAuthorName
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180205T211225Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
